In [2]:
import numpy as np
import cv2
import matplotlib.pyplot as plt

In [ ]:
print("Start!")

direc = '/home/jeff/Documents/Ultrascan/Ultrascan_Py/Plantar/Scan_3d__bmp/Scan_3d__bmp/'
Img1 = cv2.imread(direc + 'Image_0_4_0.bmp', cv2.IMREAD_GRAYSCALE) # Load image
Img2 = cv2.imread(direc + 'Image_1_5_85.bmp', cv2.IMREAD_GRAYSCALE) # Load image

plt.figure()
plt.title("Image_0_4_0.bmp")
plt.imshow(Img1)

plt.figure()
plt.title("Image_1_5_85.bmp")
plt.imshow(Img2)

In [ ]:
# Collapses the 2d array into a 1d array, then calculates histogram
Img1_hist = Img1.mean(axis=2).flatten()

plt.figure()
plt.title("Histogram of the first image")
plt.hist(Img1_hist, 255)

In [31]:

Img1_V = np.transpose(Img1, (1, 0)).flatten()

ValueError: axes don't match array

In [30]:
test = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print(test)

test_1 = np.transpose(test, (1, 0))
print(test_1)

test_1.flatten()

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


array([1, 4, 7, 2, 5, 8, 3, 6, 9])